### ISSUE TITLE
why are you using github to host a modpack

### ISSUE THREAD

**Issue by walksanatora** [MinekPo1/LSTMP#1]
also if you are going to have diffrent folders ex: client, server
just make them seperate branches
so instead of having to git clone the entire repo
you only have to clone a specific branch

**Comment by MinekPo1** [comment]
I'm sorry, but I'm surrounded by idiots

**Comment by walksanatora** [comment]
even so you can have them select the pack they want from the branches
then use the code button to download it

**Comment by MinekPo1** [comment]
Didn't feel like putting in the effort. Closing: off topic
